#!/usr/bin/env bash
#
alias b="upower -i /org/freedesktop/UPower/devices/battery_BAT0"
alias cat="bat"
alias ll='lsd   -lah'
alias l='lsd    -lFh'     #size,show type,human readable
alias la='lsd   -lAFh'   #long list,show almost all,show type,human readable
alias lr='lsd   -tRFh'   #sorted by date,recursive,show type,human readable
alias lt='lsd   -ltFh'   #long list,sorted by date,show type,human readable
#alias ll='lsd  -l'      #long list
alias ldot='lsd -ld .*'
alias lS='lsd   -lFSsh'
alias lart='lsd -lFart'
alias lrt='lsd  -lFrt'
alias vids='lsd -ltFh *.{mkv,mp4,webm}'

alias lfs='sudo /usr/sbin/chroot /mnt/lfs /usr/bin/env -i HOME=/root TERM="$TERM" PS1="\u:\w\\\\$ " PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login'

alias search_books='{ IFS= read -r d &&  find ~/Nextcloud-private/textbooks -iname "*$d*" -print; } <<<'
alias search_all='{ IFS= read -r d && sudo find / -iname "*$d*" -print; } <<<'
alias cdf='{ IFS= read -r d && cd $(find "$d" -type d | fzf); } <<<'

alias sudo='sudo '
alias grep='grep --color'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '

alias tf='tail -f'

alias '?'='duckduckgo'
alias w='wikipedia'

# Command line head / tail shortcuts
if [ -n "$ZSH_VERSION" ]; then
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"
fi
alias dud='du -d 1 -h'
alias duf='du -sh *'
alias fd='find . -type d -name'
alias ff='find . -type f -name'

if [ -n "$ZSH_VERSION" ]; then
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
fi
alias vimdiff='nvim -d'
alias cfs='nvim $HOME/dotfiles/zsh/scripts.sh'
alias cfsa='nvim -c ":vert ba" $HOME/dotfiles/zsh/scripts.sh $HOME/dotfiles_book1/zsh/scripts.sh $HOME/dotfiles_book/zsh/scripts.zsh'
alias cfsd='nvim -c ":vert ba" $HOME/dotfiles/zsh/scripts.sh $HOME/dotfiles_book/zsh/scripts.zsh'
alias cfsd1='vimdiff $HOME/dotfiles/zsh/scripts.sh $HOME/dotfiles_book1/zsh/scripts.sh'
alias cfz='nvim $HOME/dotfiles/zsh/.zshrc'
alias cfza='nvim -c ":vert ba" $HOME/dotfiles/zsh/.zshrc $HOME/dotfiles_book1/zsh/.zshrc $HOME/dotfiles_book/zsh/zshrc'
alias cfzd='nvim -c ":vert ba" $HOME/dotfiles/zsh/.zshrc $HOME/dotfiles_book/zsh/zshrc'
alias cfzd1='vimdiff $HOME/dotfiles/zsh/.zshrc $HOME/dotfiles_book1/zsh/.zshrc'
alias cfe='nvim $HOME/dotfiles/zsh/.zshenv'
alias cfea='nvim -c ":vert ba" $HOME/dotfiles/zsh/.zshenv $HOME/dotfiles_book1/zsh/.zshenv $HOME/dotfiles_book/zsh/.zshenv'
alias cfed='nvim -c ":vert ba" $HOME/dotfiles/zsh/.zshenv $HOME/dotfiles_book/zsh/.zshenv'
alias cfed1='vimdiff $HOME/dotfiles/zsh/.zshenv $HOME/dotfiles_book1/zsh/.zshenv'
alias cfl='nvim $HOME/.config/nvim/lua/custom/init.lua'
alias cfpl='nvim $HOME/.config/nvim/lua/custom/plugins.lua'
alias cfv='nvim $HOME/dotfiles/nvim/init.vim'
alias cfva='nvim -c ":vert ba" $HOME/dotfiles/nvim/init.vim $HOME/dotfiles_book1/nvim/init.vim $HOME/dotfiles_book/nvim/init.vim'
alias cfvd='nvim -c ":vert ba"  $HOME/dotfiles/nvim/init.vim $HOME/dotfiles_book/nvim/init.vim'
alias cfvd1='vimdiff $HOME/dotfiles/nvim/init.vim $HOME/dotfiles_book1/nvim/init.vim'
alias cfa='nvim $HOME/dotfiles/zsh/aliases'
alias cfaa='nvim -c ":vert ba" $HOME/dotfiles/zsh/aliases $HOME/dotfiles_book1/zsh/aliases $HOME/dotfiles_book/aliases/aliases'
alias cfad='nvim -c ":vert ba" $HOME/dotfiles/zsh/aliases $HOME/dotfiles_book/aliases/aliases'
alias cfad1='vimdiff $HOME/dotfiles/zsh/aliases $HOME/dotfiles_book1/zsh/aliases'
alias cfm='nvim $HOME/dotfiles/mutt/muttrc_local'
alias cfc='nvim $HOME/dotfiles/i3/config'
alias cfca='nvim -c ":vert ba" $HOME/dotfiles/i3/config $HOME/dotfiles_book1/i3/config $HOME/dotfiles_book/i3/config'
alias cfcd='nvim -c ":vert ba" $HOME/dotfiles/i3/config $HOME/dotfiles_book/i3/config'
alias cfcd1='vimdiff $HOME/dotfiles/i3/config $HOME/dotfiles_book1/i3/config'
alias cfx='nvim $HOME/dotfiles/X11/.Xresources'
alias cfxa='nvim -c ":vert ba" $HOME/dotfiles/X11/.Xresources $HOME/dotfiles_book1/X11/.Xresources $HOME/dotfiles_book/X11/xresources'
alias cfxd='nvim -c ":vert ba" $HOME/dotfiles/X11/.Xresources $HOME/dotfiles_book/X11/xresources'
alias cfxd1='vimdiff $HOME/dotfiles/X11/.Xresources $HOME/dotfiles_book1/X11/.Xresources'
alias cfd='nvim $HOME/dotfiles/X11/.xinitrc'
alias cfda='nvim -c ":vert ba" $HOME/dotfiles/X11/.xinitrc $HOME/dotfiles_book1/X11/.xinitrc $HOME/dotfiles_book/X11/xinitrc'
alias cfdd='nvim -c ":vert ba" $HOME/dotfiles/X11/.xinitrc $HOME/dotfiles_book/X11/xinitrc'
alias cfdd1='vimdiff $HOME/dotfiles/X11/.xinitrc $HOME/dotfiles_book1/X11/.xinitrc'
alias cfp='nvim $HOME/ArchInstall/apps.csv'
alias cfpa='nvim -c ":vert ba" $HOME/ArchInstall/apps.csv $HOME/ArchInstall_book1/apps.csv $HOME/ArchInstall_book/apps.csv'
alias cfpd='nvim -c ":vert ba" $HOME/ArchInstall/apps.csv $HOME/ArchInstall_book/apps.csv'
alias cfpd1='vimdiff $HOME/ArchInstall/apps.csv $HOME/ArchInstall_book1/apps.csv'
alias cfu='nvim $HOME/.newsboat/urls'
alias cft='nvim $HOME/.tmux.conf.local'
alias play='mono $HOME/Downloads/StarTrek/StarTrek/Program.exe'
#alias lf='ranger'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias mpdf='zathura $HOME/Nextcloud-private/mouseless/building_mouseless_environment.pdf &'
alias ppdf='zathura $HOME/Nextcloud-private/textbooks/Understanding\ Physics,\ 3\ Volumes\ in\ One\ Motion,\ Sound\ Heat\ Light,\ Magnetism\ Electricity\ The\ Electron,\ Proton\ Neutron\ by\ Isaac\ Asimov\ \(z-lib.org\).pdf &'
alias cpdf='zathura $HOME/Nextcloud-private/textbooks/chinese/Chinese\ Phrases\ For\ Dummies\ by\ Wendy\ Abraham\ \(z-lib.org\).pdf &'
alias xup='xrdb $HOME/dotfiles/X11/.Xresources'
alias pman='sudo pacman'
alias pun='sudo pacman -Rns'
alias pup='sudo pacman -Syu'
alias key='sudo pacman -S archlinux-keyring'
alias pin='pacman -Qeq'
alias paurin='pacman -Qmq'
alias pclean='sudo pacman -Sc'
alias sc='source $HOME/dotfiles/zsh/.zshrc'
alias r='ranger'
alias nb=newsboat
alias v=nvim
alias vf='nvim +FZF'
alias vi=nvim
alias vim=nvim
alias h='history -E'
alias clip='xclip -o -selection primary && echo "\r" && xclip -o -selection clipboard'
alias pop='cd ..'
alias m='cd $HOME/Music'
alias cdt='cd ~/Nextcloud-public/bimmer_docs/computer_help'
alias cda='cd ~/Nextcloud-public/bimmer_docs/scripts/arch'
alias desk='cd ~/Desktop'
alias d='dirs -v'
alias ted='tmux new-session -d -s ted "exec sudo su - teddit -c '/usr/bin/bash start_teddit.sh'"'
alias specter='tmux new-session -d -s specter "exec $HOME/Spector_chris/Specter-1.10.5.AppImage"'
alias todo='tmux new-session -d -s todo "exec python $HOME/QTodoTxt2/bin/qtodotxt.pyw"'
alias log='tmux new-session -d -s logseq "exec $HOME/logseq/Logseq-linux-x64-0.8.15.AppImage"'
alias whirl2='tmux new-session -d -s whirl "exec $HOME/Nextcloud-private/whirlpool-gui/whirlpool-gui-0.10.3.AppImage"'
alias yubi='tmux new-session -d -s yubi "exec $HOME/Downloads/yubioath-desktop-6.2.0-linux/authenticator"'
#alias bisq='tmux new-session -d -s bisq "exec /opt/bisq/bin/Bisq -btcNodes=...6id.onion:8333 -useTorForBtc=true"'
alias bisq='tmux new-session -d -s bisq "exec /opt/bisq/bin/Bisq -useTorForBtc=true"'
alias pt='tmux new-session -d -s packet "exec /opt/pt/packettracer"'
#alias wasabi='cd $HOME/WalletWasabi/WalletWasabi.Gui; dotnet run'
alias lv="nvim -c':e#<1'"
alias wea="proxychains4 curl v2.wttr.in/Phoenix\?u"
alias weat="curl v2.wttr.in/Tucson\?u"
alias weah="curl v2.wttr.in/Honolulu\?u"
alias weaf="curl v2.wttr.in/Flagstaff\?u"
alias weal="curl v2.wttr.in/Las+Vegas\?u"
alias weas="curl v2.wttr.in/Shenyang\?u"
alias weach="curl v2.wttr.in/Chengdu\?u"
alias wead="curl v2.wttr.in/Dallas\?u"
alias weac="curl v2.wttr.in/Chicago\?u"
alias weab="curl v2.wttr.in/Beijing\?u"
alias weag="curl v2.wttr.in/Mexico+City\?u"
alias weap="curl v2.wttr.in/Puerto+Vallarta\?u"
alias weachina="curl v2.wttr.in/Shen+Yang\?u"
alias weachung="curl v2.wttr.in/Chung+Qing\?u"
alias weazh="curl v2.wttr.in/Zhang+Zhou\?u"
alias weacan="curl v2.wttr.in/Cancun\?u"
alias weam="curl v2.wttr.in/Miami\?u"
alias yt='yt-dlp --add-metadata -i'
alias yta='yt -x -f bestaudio/best'
alias w5='nmcli dev wifi connect FTSESP-5G password "basicfinch431"'
alias wsl='nmcli dev wifi connect FTSESP-REMOTE-5G password "basicfinch431"'
alias xp='xprop | grep WM_CLASS'
alias phone='sshfs phone: /home/bimmer/Phone -o follow_symlinks -p 8022'
alias backup='sshfs cloud:/mnt/backup /home/bimmer/Backup'
alias backup_remote='sshfs cloud_clear:/mnt/backup /home/bimmer/Backup'
alias backup_remote_tor='torsocks sshfs cloud_tor:/mnt/backup /home/bimmer/Backup'
alias cloud='sshfs cloud:/mnt/cloud /home/bimmer/Cloud'
alias cloud_remote='sshfs cloud_clear:/mnt/cloud /home/bimmer/Cloud'
alias cloud_remote_tor='torsocks sshfs cloud_tor:/mnt/cloud /home/bimmer/Cloud'
alias prox_remote='sshfs prox_clear:/media /home/bimmer/Movies -p 49176'
alias prox2_remote='sshfs prox_clear:/media2 /home/bimmer/Movies2 -p 49176'
alias prox3_remote='sshfs prox_clear:/media2 /home/bimmer/Movies3 -p 49177'
alias sammy='sshfs samourai_vm:/home/bimmer /home/bimmer/Sammy'
alias movies='sshfs proxmox:/media /home/bimmer/Movies -p 49176'
alias movies2='sshfs proxmox:/media2 /home/bimmer/Movies2 -p 49176'
alias movies3='sshfs proxmox2:/media2 /home/bimmer/Movies3 -p 49177'
alias dc='umount /home/bimmer/Cloud'
alias vid="mpv"
alias chg_yubi='gpg-connect-agent "scd serialno" "learn --force" /bye'
alias rbt_yubi='gpg-connect-agent updatestartuptty /bye >/dev/null'
alias sudo='sudo '
